### ISSUE TITLE
[1.21][Fabric] Crash on server startup: "StampedConfig does not support valueMap() yet."

### ISSUE THREAD

**Issue by HatTrkPatrk** [Quplet/FixedVillagerTrades#4]
Env:

Java 21
Fabric 1.21, loader 0.15.11
Fabric API 0.100.7
Fixed Villager Trades 1.2.1

Getting the following error on server startup attempt which crashes the server (it does not proceed past this error):

```
[main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'fixed-villager-trades'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.15.11.jar:?]
	at net.minecraft.server.Main.main(Main.java:111) [server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.15.11.jar:?]
Caused by: java.lang.ExceptionInInitializerError
	at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
	at java.base/java.lang.Class.forName(Class.java:534) ~[?:?]
	at java.base/java.lang.Class.forName(Class.java:513) ~[?:?]
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.11.jar:?]
	... 6 more
Caused by: java.lang.UnsupportedOperationException: StampedConfig does not support valueMap() yet.
	at com.electronwill.nightconfig.core.concurrent.StampedConfig.valueMap(StampedConfig.java:472) ~[com_electronwill_night-config_core-3.7.4-40f8934727dada73.jar:?]
	at com.electronwill.nightconfig.core.utils.UnmodifiableConfigWrapper.valueMap(UnmodifiableConfigWrapper.java:29) ~[com_electronwill_night-config_core-3.7.4-40f8934727dada73.jar:?]
	at com.electronwill.nightconfig.core.ConfigSpec.isCorrect(ConfigSpec.java:546) ~[com_electronwill_night-config_core-3.7.4-40f8934727dada73.jar:?]
	at qu.fixedVillagerTrades.config.ModConfig.checkConfig(ModConfig.java:33) ~[fixed-villager-trades-1.2.1.jar:?]
	at qu.fixedVillagerTrades.config.ModConfig.<init>(ModConfig.java:20) ~[fixed-villager-trades-1.2.1.jar:?]
	at qu.fixedVillagerTrades.FixedVillagerTrades.<clinit>(FixedVillagerTrades.java:16) ~[fixed-villager-trades-1.2.1.jar:?]
	at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
	at java.base/java.lang.Class.forName(Class.java:534) ~[?:?]
	at java.base/java.lang.Class.forName(Class.java:513) ~[?:?]
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.11.jar:?]
	... 6 more
```

**Comment by Quplet** [comment]
Should be fixed with 1.2.2
